### ISSUE TITLE
Make "store" and "sessionUserId" the first optional TelegramClient parameters back

### ISSUE THREAD

**Issue by Laiteux** [nblockchain/TgSharp#21]
I disagree with the commit 73313ae199ffc96811ebf22c1f84329696d26c7a.

I think the way it was before was easier for **3** reasons:

1. I personally, and believe most users do as well, use the `store` and `sessionUserId` parameters a lot more than `dcIpVersion`, which we really tend to keep set to `DataCenterIPVersion.Default` by default.

2. It was easier and shorter, previously, to write `new TelegramClient(0, "", dcIpVersion: DataCenterIPVersion.Whatever)` to customize `dcpIpVersion`, than it is now if we only want to customize our session stuff: `new TelegramClient(0, "", store: new WhateverSessionStore(), sessionUserId: "Laiteux")`, due to the fact these 2 parameters are frequently used together. What I mean is that `new TelegramClient(0, "", new WhateverSessionStore(), "Laiteux")` was previously shorter to write than it is now.

3. I believe the `dcIpVersion` parameter should remain next to `handler`, as they both are related and usually used together.
Also, for example, when setting the `handler` parameter to use a custom TcpClient (let's say one using a proxy), you most likely want to set `dcpIpVersion` to `DataCenterIPVersion.IPv4` as well, unless your proxy also supports IPv6 (rare afaik).

Please let me know what you think.

**Comment by Laiteux** [comment]
By the way, I believe `sessionUserId` should be renamed to something like `sessionId` (which stands for "session identifier"), which sounds more adapted in my opinion. (:

**Comment by aarani** [comment]
@knocte yeah, dcIpVersion should not be the first parameters, it doesn't matter if it's more important, sessionId and store are more prone to changes.

**Comment by knocte** [comment]
> I believe sessionUserId should be renamed to something like sessionId

how about `userSessionId`?

> sessionId and store are more prone to changes.

what do you exactly mean with "more prone to changes"?

**Comment by Laiteux** [comment]
> > I believe sessionUserId should be renamed to something like sessionId
> 
> 
> 
> how about `userSessionId`?

I think we should actually rename both session parameters: `sessionStore` (instead of simply `store`) and `sessionId` so it matches

**Comment by aarani** [comment]
> > I believe sessionUserId should be renamed to something like sessionId
> 
> how about `userSessionId`?
> 

auth_key/Session isn't related to user / authentication it belongs to transport authorization you can use some functions without even having a user logged in.
 
> what do you exactly mean with "more prone to changes"?

store and sessionId default value are just for testing, any production users should change / pass that parameter, but dcpIpVersion  default value is Ok for most people.
