### ISSUE TITLE
Disconnect client

### ISSUE THREAD

**Issue by atrdev-rgb** [nblockchain/TgSharp#37]
How to make an exit request so that the active session is not in the list of devices?

**Comment by ng-designs** [comment]
Maybe this can help you:

```
public static async Task<bool> Logout(TLInputPeerUser usr)
        {

            var req = new TLRequestLogOut();

            //run request, and deserialize response to Boolean
            return await client.SendRequestAsync<Boolean>(req);
        }
```

**Comment by atrdev-rgb** [comment]
> Maybe this can help you:
> 
> ```
> public static async Task<bool> Logout(TLInputPeerUser usr)
>         {
> 
>             var req = new TLRequestLogOut();
> 
>             //run request, and deserialize response to Boolean
>             return await client.SendRequestAsync<Boolean>(req);
>         }
> ```

вы правы, спасибо. Однако TLInputPeerUser usr тут избыточен, и Boolean не всегда возвращается, поэтому я вышел из положения dynamic
