### ISSUE TITLE
FwdFrom.FromName всегда возвращает Null

### ISSUE THREAD

**Issue by ng-designs** [nblockchain/TgSharp#38]
Пытаюсь получить информацию об авторе сообщения, от которого оно было переслано в канал. Но поле FromName всегда возвращает null. Есть ли какое-либо решение данной проблемы?

Собрал библиотеку с последними изменениями. Может ли быть проблема в том что запрос отправляется в формате более нового layer чем получает?

**Comment by atrdev-rgb** [comment]
Если этот пользователь скрыл о себе данные конфиденциальности, то ничего вы не получите. Политика безопасности Telegram. Если же пользователь ничего о себе не скрывал, то вы все увидеть должны. \или у вас что-то не то со сборкой
