### ISSUE TITLE
NullRefrenceException in BigInteger.cs in CompareTo method after forking the library and update it to layer 121

### ISSUE THREAD

**Issue by Muaath5** [nblockchain/TgSharp#40]
Hi,
## Error position
![Stack trace](https://user-images.githubusercontent.com/60256639/109410419-a59f9680-79ab-11eb-9889-ef169031570e.png)
**File:** I Run it and I am getting error in `BigInteger.cs` file.
**Line in `BigInteger.cs`:** In line 344 in constructor (`ctor`) when calling `Pow` method.
**Method:** Inside method `CompareTo` method.

Error: `NullRefrenceException`

Stack trace is in photo above

**NOTE:** `Pow` method is using `Equals` method that uses `CompareTo` method.

## Source code
`CompareTo` method source:
```c#
public int CompareTo(BigInteger value)
{
    return sign < value.sign ? -1
        : sign > value.sign ? 1
        : sign == 0 ? 0
        : sign * CompareNoLeadingZeroes(0, magnitude, 0, value.magnitude);
}
```
Line 344, in constructor (`ctor`):
```c#
b = b.Multiply(r.Pow(s.Length)); // HERE is an error
```

I am thinking the error is in `sign` variable, But how can I fix it?

**Comment by aarani** [comment]
You have to give more context (like what changes you made to the authentication part of the code which is the only place we use BigInteger.cs for) also your fork breaks compatibility with our repo which makes it even harder to compare it.
What I can tell you with 100% confidence is that I have upgraded this library to layer 121 and targeted .NET standard and It didn't break on me.

**Comment by Muaath5** [comment]
> You have to give more context (like what changes you made to the authentication part of the code which is the only place we use BigInteger.cs for) also your fork breaks compatibility with our repo which makes it even harder to compare it.
> What I can tell you with 100% confidence is that I have upgraded this library to layer 121 and targeted .NET standard and It didn't break on me.

àa

**Comment by Muaath5** [comment]
> You have to give more context (like what changes you made to the authentication part of the code which is the only place we use `BigInteger.cs` for) also your fork breaks compatibility with our repo which makes it even harder to compare it.
> What I can tell you with 100% confidence is that I have upgraded this library to layer 121 and targeted .NET standard and It didn't break on me.

You can see my new library link in GitHub.

https://github.com/Muaath5/TgSharp.NETCore

**Comment by Muaath5** [comment]
> You have to give more context (like what changes you made to the authentication part of the code which is the only place we use BigInteger.cs for) also your fork breaks compatibility with our repo which makes it even harder to compare it.
> What I can tell you with 100% confidence is that I have upgraded this library to layer 121 and targeted .NET standard and It didn't break on me.

You can see my new kibrary link in GitHub.

https://github.com/Muaath5/TgSharp.NETCore
