### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'TeleSharp.TL

### ISSUE THREAD

**Issue by VictorShap** [nblockchain/TgSharp#8]
When program runs this method, i receive an exception :System.IO.FileNotFoundException: Could not load file or assembly 'TeleSharp.TL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.Cannot find the specified file.
File name: 'TeleSharp.TL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at TgSharp.Core.TelegramClient.ConnectInternalAsync(Boolean reconnect, CancellationToken token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TgSharp.Core.TelegramClient.ConnectInternalAsync(Boolean reconnect, CancellationToken token)
   at TgSharp.Core.TelegramClient.ConnectAsync(CancellationToken token)
   at ConsoleApp1.Program.RunClient() in C:\Users\myUser\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 19
My code: 
using System;
using System.Threading.Tasks;
using TgSharp.Core;

namespace ConsoleApp1
{
    class Program
    {
        private const int apiId = ;
        private const string apiHash = "";
        private const string phoneNumber = "";
        static void Main(String[] args) => RunClient();

        public static async void RunClient()
        {
            try
            {
                var client = new TelegramClient(apiId, apiHash);
                await client.ConnectAsync();
                var hash = await client.SendCodeRequestAsync(phoneNumber);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }

        }
    }
}

**Comment by VictorShap** [comment]
Have you fixed this or why did you close this?

**Comment by knocte** [comment]
I think I fixed it in version 0.1.1--date20200416-1121.git-58df196 which is now in nuget, can you check?

**Comment by VictorShap** [comment]
Yes, I haven’t this problem, but now my void RunClient does not run, program stops on RunClient()

**Comment by knocte** [comment]
If the FileNotFoundException issue is fixed, let's stop chatting here.

For the "program stops" issue, you have to find an exception, no .NET program can stop without running an exception. When you find it, open a new issue.
