### ISSUE TITLE
ConnectAsync()

### ISSUE THREAD

**Issue by VictorShap** [nblockchain/TgSharp#9]
ConnectAsync() doesn't work, when program starts doing this method, program stops
My code : 
        using System;
        using System.Threading.Tasks;
        using TgSharp.Core;
        

        namespace ConsoleApp1
        {
            class Program
            {
                private const int apiId = ;
                private const string apiHash = "";
                private const string phoneNumber = "";
                static void Main(String[] args)
                {
            
                    RunClient();
                }
                public static async void RunClient()
                {
            

                    var client = new TelegramClient(apiId, apiHash);
                    await client.ConnectAsync();           
                    var hash = await client.SendCodeRequestAsync(phoneNumber);
         

                }
            }
        }

**Comment by VictorShap** [comment]
![image](https://user-images.githubusercontent.com/36379638/79459722-64ed9780-7ffc-11ea-97c6-242a644357fb.jpeg)
![image](https://user-images.githubusercontent.com/36379638/79459734-6919b500-7ffc-11ea-8114-f2ff8e1fcaa7.jpeg)
![Uploading 79459776...]()

**Comment by VictorShap** [comment]
![Uploading 79459828...]()

**Comment by Azhe403** [comment]
async function need await when calling that function.
you should use `await RunClient()`.

change Task type instead of void on RunClient()

**Comment by Laiteux** [comment]
@knocte I'd close this. inactivity + solved by @Azhe403
